### ISSUE TITLE
Twitch API update

### ISSUE THREAD

**Issue by colehammond65** [mortenmoulder/TwitchClipper#4]
The legacy Twitch API has been shut down which has stopped TwitchClipper from working, Could it be updated to the new API?

Info: https://blog.twitch.tv/en/2021/07/15/legacy-twitch-api-v5-shutdown-details-and-timeline/

**Comment by mortenmoulder** [comment]
I will take a look at this later. I'm pretty sure I'm already on the new API, as I'm definitely not using v5, but maybe I missed something.

**Comment by colehammond65** [comment]
Sounds good, this is the error I'm getting as of today if it helps:

`Grabbing the broadcaster's ID.System.Net.Http.HttpRequestException: Response status code does not indicate success: 401 (Unauthorized).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at System.Net.Http.HttpClient.GetStringAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at TwitchClipper.Services.TwitchAPIService.GetBroadcasterId(String username)
   at TwitchClipper.Application.Run(Options options)
   at TwitchClipper.Program.Main(String[] args)`

**Comment by mortenmoulder** [comment]
It works fine for me. Is this the first time using TwitchClipper, or has it worked before and now it suddenly doesn't work?

Remember to change the `appsettings.json` to include the client_id and client_secret, as per the configuration section: https://github.com/mortenmoulder/TwitchClipper#configuration

**Comment by colehammond65** [comment]
I have been using TwitchClipper almost daily for months, it's been working perfectly until today. I have double checked the appsettings.json and its correct

**Comment by mortenmoulder** [comment]
Try generating a new secret and using that instead. I just did using the latest code changes in this repository and it works for me. Maybe Twitch invalidated your credentials?

https://dev.twitch.tv/console/apps

EDIT: https://dev.twitch.tv/docs/authentication
>App access tokens expire after about 60 days, so you should check that your app access token is valid by submitting a request to the validation endpoint (see [Validating Requests](https://dev.twitch.tv/docs/authentication#validating-requests)). If your token has expired, generate a new one.

Maybe I should send a request to that endpoint, then notify the user in the console, that the access token has expired and that they need a new secret. I'll look into that later.

**Comment by colehammond65** [comment]
Perfect, new creds fixed it. Cheers for the help and keep up the good work.

**Comment by mortenmoulder** [comment]
Awesome!

I'll look into validating and update the repository asap. Thanks.
