### ISSUE TITLE
Program instantly says downloads complete but does not download anything

### ISSUE THREAD

**Issue by colehammond65** [mortenmoulder/TwitchClipper#5]
OS: Debian 11
Version: 1.0.6

When I run the program, it finds all the clips, saves them to logs.json. logs.json has syntax errors, but even after fixing them and running the program again, it says the clips are being downloaded but they 'comeplete' instantly and doesnt download anything, ./clips/username/date folders are empty

**Comment by mortenmoulder** [comment]
@colehammond65 Do you mind sharing the user you're inputting? Also, if you made a custom save expression, let me know what it looks like. Thanks.

**Comment by colehammond65** [comment]
No custom expression(s). Twitch user is mmarshyellow

Logs:
`cole@Sersi:~/Share/Projects Archive/Marshy/TwitchClipper$ ./TwitchClipper -u mmarshyellowellow
Downloading clips made by mmarshyellow
Grabbing the broadcaster's ID.
Scraping Twitch for clips. A total of 314 requests must be sent!

Clips found: 452 - Page 314/314
Creating directories. This might take a while.
Found a total of 452 clips and 450 already exists. Downloading 2 clips.
Downloading clip 2/2 using 5 download threads
Done!`

Looks good but the two clips it said it downloaded were not, the folder of the date of the clips is created, but it is empty

**Comment by mortenmoulder** [comment]
@colehammond65 Try again. It should prompt you to update. I did some retry logic to the requests, because a lot failed for me.

I can't replicate your issue, unfortunately:

```
Clips found: 452 - Page 313/314
Creating directories. This might take a while.
Found a total of 452 clips and 452 already exists. Downloading 0 clips.
```

Can you find the URL/name/anything on the 2 clips you can't download?

**Comment by mortenmoulder** [comment]
@colehammond65 Assuming this is not an issue anymore. Let me know and I will re-open it.
