### ISSUE TITLE
Request: Add support for "uploader" variable

### ISSUE THREAD

**Issue by LuminairPrime** [mortenmoulder/TwitchClipper#6]
Yt-dlp/Youtube DL support an "uploader" variable, which in the case of Twitch clips is the username of the clip creator. This would be good to add to the TwitchClipper naming documentation! :) https://github.com/mortenmoulder/TwitchClipper/wiki/Custom-save-expressions

Bonus request: I also use yt-dlp's "id" variable, which in the case of Twitch clips gives a unique numerical value, rather than the unique word string from the URL.

Example usage from yt-dlp documentation:
> uploader (string): Full name of the video uploader
> yt-dlp -o "%(uploader)s"

https://github.com/yt-dlp/yt-dlp#output-template

**Comment by mortenmoulder** [comment]
Done 😃  I have added `uploader` as an expression you can use, however, the id you get from yt-dlp does not exist in the API request from Twitch:

![image](https://user-images.githubusercontent.com/1304665/196299262-593d13e1-5504-4a3a-bf77-ebc662549caa.png)

I'm not sure where to get it from, unfortunately. I am not going to mess with the yt-dlp parameters, as I bet that will only complicate it further.

**Comment by LuminairPrime** [comment]
To address what the number ID is for: I simply use it as a unique value to differentiate clip filenames. I don't actually use it to visit a URL or whatever, though maybe that works too. In any case, I agree with your first judgement that just using the URL string makes a lot more sense, haha, it just happens to make a really long filename and I didn't go with it for my current naming schema.

You are an incredible developer, by the way! Super quick work!!! I don't know C#, but I can tell that you're a professional from the design of the project. Great contribution to github 👍

**Comment by mortenmoulder** [comment]
@LuminairPrime Thanks for the kind words! I do work with .NET every day, but this project is definitely not one of the pretty ones. It was made for a friend, and I decided to expand it a bit and release it as a project. A lot of annoying hacks, but if it works.. no point changing it now 😆

I'm not a huge fan of using other variables than the ones Twitch sends. I could make a hash function that generates a numeric value based on some of the data, but I don't like it. I like it for the "randomness" (say you just want to dump EVERYTHING into one folder), but I don't think I'll be implementing something like that. Sorry 😞
