### ISSUE TITLE
Request: Migrate from youtube-dl to yt-dlp

### ISSUE THREAD

**Issue by LuminairPrime** [mortenmoulder/TwitchClipper#7]
It seems that the community has forked youtube-dl due to lack of activity by the maintainer. Yt-dlp seems to be more actively updated now, so it would be good to use it.

https://github.com/yt-dlp/yt-dlp

Workaround: In the mean time, I've downloaded and renamed yt-dlp.exe to youtube-dl.exe in the TwitchClipper directory, and that works fine!

**Comment by mortenmoulder** [comment]
Done. The new version should now download yt-dlp instead 😃
